Resize fixes
playtron-os/playtron-os-scripts pull request #5
Opened 2023-10-10 22:48 UTC by LukeShortCloud

Creating swap can accidentally fill up a storage device. We now check to see how much storage is available first.

2023-10-10 22:49 UTC, LukeShortCloud commented
I've been testing this out today. I found an edge case where `df -h` reported that I had 51 GB of storage space when I actually had 5.1 GB.

2023-10-10 23:10 UTC, LukeShortCloud commented
I also found a syntax issue with the `if` statement for comparing the file size. Everything seems to working good now based on my local testing.

2023-10-13 14:14 UTC, alkazar requested changes

2023-10-13 14:14 UTC, alkazar commented on sbin/create-swap.sh
> +root_size=$(df -h | grep -P '\/$' | awk '{print $4}')
In ostree based systems `df` output shows the root as mounted on `/sysroot`, there is actually no entry shown to be mounted on `/`. I verified this both on my Silverblue install and on a PlaytronOS install.

This script is run post-install on first boot inside PlaytronOS, so we need to test in that environment.

2023-10-13 14:14 UTC, alkazar commented on sbin/create-swap.sh
> +if [ $? -eq 0 ]; then
Alternatively, you could do (same for the similar conditional below):
`if echo ${root_size} | grep -P 'G$'; then`

2023-10-13 14:17 UTC, alkazar commented
>     * If the root file system is in terabytes (too big) or megabytes (too small), do not create swap.

This is incorrect. The script creates swap if the remaining storage size is in terabytes. It doesn't do an explicit check for the Terabyte or Megabyte case, but the result is different between the two cases.

2023-10-13 14:18 UTC, alkazar requested changes

2023-10-13 14:18 UTC, alkazar commented on sbin/create-swap.sh
> +# If the root file system size is in gigabytes (not terabytes), we need to make sure there is enough space.
"root file system size" is inaccurate. What we are looking at is "root file system available space"

2023-10-13 23:58 UTC, LukeShortCloud commented
Apologies for the confusion. You're right, my statement was technically not correct. I do not check for terabytes but I do check for the case of megabytes (and gigabytes). Anything larger than gigabytes (terabytes, petabytes, and beyond), we can safely assume that there is enough space available. Anything that is in gigabytes, we need to manually check. Anything that is megabytes is too small. I don't check for kilobytes which might be an edge case. I imagine a user wouldn't be able to boot with that low of storage space.

I did testing on an Playtron OS build with the latest updates. Now it works in an rpm-ostree world. :-)

2023-10-17 17:02 UTC, merged